name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  ci:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
